name: dataprep
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - polars
  - pyarrow
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - quarto
platforms:
  - osx-arm64
  - linux-64
  - win-64